name: Docker Build

on: [pull_request]

jobs:
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker build
        run: make docker-build
      - name: Run database
        run: docker-compose up -d db
      - name: Test migration
        run: |
          sleep 10
          docker run --rm --network host -e DATABASE_USER=vdbm -e DATABASE_PASSWORD=password \
          -e DATABASE_HOSTNAME=127.0.0.1 -e DATABASE_PORT=5432 -e DATABASE_NAME=vulcanize_public \
          vulcanize/statediff-migrations
      - name: Verify schema is latest
        run: |
          PGPASSWORD="password" pg_dump -h localhost -p 5432 -U vdbm vulcanize_public --no-owner --schema-only > schema.sql
          ./scripts/check_diff.sh db/schema.sql schema.sql
      - name: Verify up and down migration
        run: |
          timeout 5m make test-migrations